#!/usr/bin/env bash

bazel clean && \
    bazel build \
    --features=compiler_param_file \
    --remote_executor=grpc://localhost:8980 \
    --remote_instance_name="" \
    --platforms=@io_bazel_rules_go//go/toolchain:windows_amd64 \
    --extra_execution_platforms=//tools/remote-toolchains:windows-platform \
    "$@"
